In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0                    motthegioi.vn        0        0           1          2   
1                  sourceforge.net        0        0           1          3   
2                     logex.com.tr        0        0           1          2   
3                    filehippo.com        0        0           1          4   
4  realestate-page.us.alapinta.com        0        0           0          0   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           1            1   
1            0             0        0              0           1            1   
2            0             0        1              0           0            1   
3            0             0        0              0           0            1   
4            0             0        0              1           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           1           1       0           0            1             0   
1           1           1       0           0            1             0   
2           0           1       0           0            1             1   
3           1           1       0           0            1             0   
4           0           0       0           0            1             0   

   Label  
0      0  
1      0  
2      1  
3      0  
4      1

In [4]:
X = data.drop(['Domain', 'Label'], axis=1)

In [ ]:
X.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      141              0              0        0  30.0   
1      151             70             40      271  41.8   
2       84             90             23       56  39.5   
3       80             55              0        0  19.1   
4      128             80              0        0  34.6   

   DiabetesPedigreeFunction  Age  
0                     0.761   27  
1                     0.742   38  
2                     0.159   25  
3                     0.258   21  
4                     0.144   45

In [5]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [7]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [9]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.803
Precision: 0.8278412521887274
Recall: 0.803
F1 Score: 0.7999927259634724
Confusion Matrix:
[[1372   93]
 [ 498 1037]]

SVC Metrics:
Accuracy: 0.839
Precision: 0.8711782774914336
Recall: 0.839
F1 Score: 0.8360874096802696
Confusion Matrix:
[[1442   23]
 [ 460 1075]]

RandomForestClassifier Metrics:
Accuracy: 0.8613333333333333
Precision: 0.869557985500636
Recall: 0.8613333333333333
F1 Score: 0.8608350159469594
Confusion Matrix:
[[1366   99]
 [ 317 1218]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8543333333333333
Precision: 0.8675744073706149
Recall: 0.8543333333333333
F1 Score: 0.8533849561038042
Confusion Matrix:
[[1386   79]
 [ 358 1177]]

KNeighborsClassifier Metrics:
Accuracy: 0.8543333333333333
Precision: 0.8631062980313909
Recall: 0.8543333333333333
F1 Score: 0.8537549253876905
Confusion Matrix:
[[1360  105]
 [ 332 1203]]

DecisionTreeClassifier Metrics:
Accuracy: 0.862
Precision: 0.8708461368526765
Recall: 0.862
F1 Score: 0.861457942275914
Confusion Matrix:
[[1371   94]
 [ 320 1215]]


In [10]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
5  DecisionTreeClassifier  0.862000   0.870846  0.862000  0.861458
2  RandomForestClassifier  0.861333   0.869558  0.861333  0.860835
3           MLPClassifier  0.854333   0.867574  0.854333  0.853385
4    KNeighborsClassifier  0.854333   0.863106  0.854333  0.853755
1                     SVC  0.839000   0.871178  0.839000  0.836087
0      LogisticRegression  0.803000   0.827841  0.803000  0.799993
